// Book intros — author, date, audience, themes, key verses for each NT book + selected OT
// Used by the Biblical AI Search engine for "book audience"-style questions.

export const BOOK_INTROS = {
  Romans: {
    author: 'The Apostle Paul',
    date: 'c. 56-58 AD',
    audience: 'Roman Christians — a mixed congregation of Jewish and Gentile believers in the imperial capital. Paul had not yet visited Rome and wrote partly to introduce himself before a planned visit (Rom 1:8-15, 15:22-29).',
    purpose: "To present a comprehensive exposition of the Gospel: humanity's universal sinfulness, justification by faith in Christ, sanctification by the Spirit, the security of the believer, God's plan for Israel, and the practical outworking of grace in daily life.",
    themes: ['Justification by faith', 'Universal sinfulness', 'Sanctification', 'Election and Israel', 'Practical Christian living'],
    keyVerses: ['Romans 1:16-17', 'Romans 3:23', 'Romans 5:1', 'Romans 6:23', 'Romans 8:1', 'Romans 8:28', 'Romans 10:9-10', 'Romans 12:1-2'],
    structure: 'Chs 1-3: Sin (the problem) | 4-5: Justification by faith | 6-8: Sanctification | 9-11: Israel and election | 12-16: Application',
  },
  '1 Corinthians': {
    author: 'The Apostle Paul',
    date: 'c. 53-55 AD',
    audience: 'The church in Corinth — a wealthy, multicultural Roman colony notorious for sexual immorality and pagan worship. Paul founded this church on his second missionary journey (Acts 18).',
    purpose: 'To address divisions, immorality, lawsuits, marriage questions, idol meat, public worship abuses, the resurrection, and proper use of spiritual gifts.',
    themes: ['Christian unity', 'Sexual purity', 'The resurrection of Christ', 'Spiritual gifts', 'Love (chapter 13)'],
    keyVerses: ['1 Corinthians 1:18', '1 Corinthians 6:19-20', '1 Corinthians 10:13', '1 Corinthians 13:4-7', '1 Corinthians 15:3-4', '1 Corinthians 15:51-57'],
  },
  '2 Corinthians': {
    author: 'The Apostle Paul', date: 'c. 55-56 AD',
    audience: 'The Corinthian church, after a painful confrontation. Paul defends his apostolic ministry against false teachers and asks for forgiveness for previous strict correction.',
    purpose: 'A deeply personal letter defending Paul\'s ministry, encouraging generosity in giving, and exposing the false "super-apostles" who were undermining his authority.',
    themes: ['Suffering and comfort', 'Reconciliation', 'Generosity', 'Apostolic authenticity', 'New covenant ministry'],
    keyVerses: ['2 Corinthians 4:7', '2 Corinthians 5:17', '2 Corinthians 5:21', '2 Corinthians 9:7', '2 Corinthians 12:9'],
  },
  Galatians: {
    author: 'The Apostle Paul', date: 'c. 48-49 AD (one of his earliest letters)',
    audience: 'The churches of Galatia (modern central Turkey) — converts being misled by Judaizers who insisted Gentile Christians must keep the Mosaic Law to be saved.',
    purpose: 'To passionately defend justification by faith alone — not by works of the Law. Often called "the Magna Carta of Christian liberty."',
    themes: ['Justification by faith', 'Christian liberty', 'Fruit of the Spirit', 'No other Gospel'],
    keyVerses: ['Galatians 2:20', 'Galatians 3:13', 'Galatians 5:1', 'Galatians 5:22-23', 'Galatians 6:7-8'],
  },
  Ephesians: {
    author: 'The Apostle Paul', date: 'c. 60-62 AD (from Roman imprisonment)',
    audience: 'Believers in Ephesus — the leading city of Asia Minor and a major center of pagan religion (Temple of Artemis). Possibly a circular letter for several churches.',
    purpose: 'To exalt the cosmic Christ and the eternal purposes of God in uniting Jew and Gentile in one new people. Doctrine in chs 1-3, application in 4-6.',
    themes: ['God\'s eternal purpose', 'Unity in Christ', 'Spiritual blessings', 'The church as Christ\'s body', 'Spiritual warfare'],
    keyVerses: ['Ephesians 1:3-14', 'Ephesians 2:8-10', 'Ephesians 4:1-6', 'Ephesians 5:25', 'Ephesians 6:10-18'],
  },
  Philippians: {
    author: 'The Apostle Paul', date: 'c. 60-62 AD (from prison)',
    audience: 'The Philippian church — Paul\'s most beloved congregation, founded on his second journey (Acts 16). They had sent gifts to support him in prison.',
    purpose: 'A warm thank-you letter overflowing with joy despite Paul\'s chains. Encourages believers to find their joy in Christ in any circumstance.',
    themes: ['Joy in Christ', 'Humility', 'Contentment', 'Christ-centered living'],
    keyVerses: ['Philippians 1:21', 'Philippians 2:5-11', 'Philippians 3:7-10', 'Philippians 4:6-7', 'Philippians 4:13', 'Philippians 4:19'],
  },
  Colossians: {
    author: 'The Apostle Paul', date: 'c. 60-62 AD (from prison)',
    audience: 'The Colossian church — facing a syncretistic heresy mixing Christianity with Jewish ritual, Greek philosophy, and angel worship.',
    purpose: 'To exalt the supremacy and sufficiency of Christ against the "Colossian heresy." Christ alone — nothing more is needed.',
    themes: ['Supremacy of Christ', 'Fullness in Christ', 'New life in Christ'],
    keyVerses: ['Colossians 1:15-20', 'Colossians 2:9-10', 'Colossians 3:1-2', 'Colossians 3:23-24'],
  },
  '1 Thessalonians': {
    author: 'The Apostle Paul', date: 'c. 51 AD (Paul\'s earliest surviving letter)',
    audience: 'Newly converted believers in Thessalonica — a strategic Roman provincial capital. Paul had only spent a few weeks with them before being driven out (Acts 17).',
    purpose: 'To encourage young believers, answer questions about the Second Coming, and address concerns about believers who had died.',
    themes: ['The Second Coming', 'Holy living', 'Brotherly love', 'Hope in death'],
    keyVerses: ['1 Thessalonians 4:13-18', '1 Thessalonians 5:16-18', '1 Thessalonians 5:23'],
  },
  '2 Thessalonians': {
    author: 'The Apostle Paul', date: 'c. 51-52 AD',
    audience: 'The same Thessalonian church, now troubled by false teachings that the Day of the Lord had already come.',
    purpose: 'To correct end-times confusion and rebuke idleness among those who had stopped working in expectation of an imminent return.',
    themes: ['The Day of the Lord', 'Man of sin', 'Discipline of idleness'],
    keyVerses: ['2 Thessalonians 2:1-12', '2 Thessalonians 3:10'],
  },
  '1 Timothy': {
    author: 'The Apostle Paul', date: 'c. 62-64 AD',
    audience: 'Timothy — Paul\'s young protégé pastoring the Ephesian church. A pastoral epistle.',
    purpose: 'Practical instruction for church order, qualifications for elders and deacons, sound doctrine, and confronting false teachers.',
    themes: ['Sound doctrine', 'Church leadership', 'Pastoral conduct', 'Godliness'],
    keyVerses: ['1 Timothy 1:15', '1 Timothy 2:5-6', '1 Timothy 3:1-13', '1 Timothy 6:6-10'],
  },
  '2 Timothy': {
    author: 'The Apostle Paul', date: 'c. 66-67 AD (Paul\'s final letter, written shortly before his execution)',
    audience: 'Timothy again — Paul\'s last words to his spiritual son.',
    purpose: 'A deeply personal farewell. Paul charges Timothy to guard the Gospel, endure suffering, and finish his race well.',
    themes: ['Endurance in suffering', 'Guarding the Gospel', 'Inspiration of Scripture', 'Faithful finish'],
    keyVerses: ['2 Timothy 1:7', '2 Timothy 2:15', '2 Timothy 3:16-17', '2 Timothy 4:7-8'],
  },
  Titus: {
    author: 'The Apostle Paul', date: 'c. 62-64 AD',
    audience: 'Titus — appointed by Paul to organize the church on Crete, a notoriously immoral culture.',
    purpose: 'Practical instructions for church order in a difficult cultural setting; emphasis on good works as evidence of saving grace.',
    themes: ['Church order', 'Sound doctrine', 'Good works', 'Salvation by grace'],
    keyVerses: ['Titus 2:11-14', 'Titus 3:5-7'],
  },
  Philemon: {
    author: 'The Apostle Paul', date: 'c. 60-62 AD',
    audience: 'Philemon — a wealthy Christian in Colossae whose runaway slave Onesimus had become a believer under Paul\'s ministry.',
    purpose: 'A masterpiece of Christian persuasion. Paul appeals to Philemon to receive Onesimus back not as a slave but as a brother in Christ.',
    themes: ['Christian forgiveness', 'Brotherhood in Christ', 'Christian transformation'],
    keyVerses: ['Philemon 1:10-18'],
  },
  Hebrews: {
    author: 'Unknown — possibly Paul, Apollos, Barnabas, or Priscilla. The early church was uncertain.',
    date: 'c. 60s AD (before the destruction of the Temple in 70 AD, since the Temple sacrificial system is described in present tense)',
    audience: 'Jewish Christians tempted to revert to Judaism under persecution. The book defends Christ\'s superiority over every Jewish institution.',
    purpose: 'To prove the supremacy of Christ over angels, Moses, the priesthood, sacrifices, and the Old Covenant — and warn against falling away.',
    themes: ['Supremacy of Christ', 'New Covenant', 'Faith (chapter 11)', 'Endurance', 'Better priesthood'],
    keyVerses: ['Hebrews 1:1-3', 'Hebrews 4:12', 'Hebrews 4:15-16', 'Hebrews 9:27-28', 'Hebrews 11:1', 'Hebrews 12:1-2'],
  },
  James: {
    author: 'James, the brother of Jesus and leader of the Jerusalem church',
    date: 'c. 45-49 AD (likely the earliest New Testament book)',
    audience: 'Jewish Christians scattered abroad ("the twelve tribes which are scattered abroad" — James 1:1).',
    purpose: 'A practical handbook of Christian ethics. James writes like an Old Testament prophet — calling believers to live out their faith in works.',
    themes: ['Faith and works', 'Trials and temptation', 'The tongue', 'Wealth and the poor', 'Prayer'],
    keyVerses: ['James 1:2-4', 'James 1:22', 'James 2:17', 'James 3:5-6', 'James 4:7-8', 'James 5:16'],
  },
  '1 Peter': {
    author: 'The Apostle Peter',
    date: 'c. 62-64 AD',
    audience: 'Suffering Christians scattered across Asia Minor (modern Turkey), facing persecution under Nero.',
    purpose: 'To encourage suffering believers that their trials are purposeful and their hope in Christ is secure.',
    themes: ['Suffering for Christ', 'Living hope', 'Holy living', 'Submission'],
    keyVerses: ['1 Peter 1:3-9', '1 Peter 2:9-10', '1 Peter 3:15', '1 Peter 5:7'],
  },
  '2 Peter': {
    author: 'The Apostle Peter',
    date: 'c. 64-67 AD (shortly before his martyrdom)',
    audience: 'The same scattered believers — now also threatened by false teachers within the church.',
    purpose: 'To equip believers to recognize and resist false teachers and to remind them of Christ\'s certain return.',
    themes: ['Christian growth', 'False teachers', 'The Day of the Lord'],
    keyVerses: ['2 Peter 1:3-4', '2 Peter 1:20-21', '2 Peter 3:9'],
  },
  '1 John': {
    author: 'The Apostle John',
    date: 'c. 85-95 AD',
    audience: 'Churches in Asia Minor under attack from early Gnostic teachers who denied Christ\'s humanity.',
    purpose: 'To assure believers of their salvation and refute Gnostic heresy. Tests of authentic faith: love, obedience, and right doctrine.',
    themes: ['Assurance of salvation', 'Love', 'Obedience', 'Truth vs. error'],
    keyVerses: ['1 John 1:9', '1 John 3:1-2', '1 John 4:7-8', '1 John 4:19', '1 John 5:11-13'],
  },
  '2 John': {
    author: 'The Apostle John',
    date: 'c. 85-95 AD',
    audience: '"The elect lady and her children" — possibly a specific woman, possibly a personification of a local church.',
    purpose: 'A short warning against false teachers and an exhortation to walk in love and truth.',
    themes: ['Truth and love', 'Hospitality and discernment'],
    keyVerses: ['2 John 1:6', '2 John 1:9-10'],
  },
  '3 John': {
    author: 'The Apostle John',
    date: 'c. 85-95 AD',
    audience: 'Gaius — a beloved Christian who was hospitable to traveling missionaries.',
    purpose: 'To commend Gaius, expose the proud Diotrephes, and recommend Demetrius.',
    themes: ['Hospitality', 'Walking in truth', 'Faithful service'],
    keyVerses: ['3 John 1:4', '3 John 1:11'],
  },
  Jude: {
    author: 'Jude, the brother of Jesus and James',
    date: 'c. 65-80 AD',
    audience: 'The general Christian church, addressing infiltration by false teachers.',
    purpose: 'A passionate call to "contend for the faith" against apostates who had crept into the church.',
    themes: ['Contending for the faith', 'False teachers', 'Judgment', 'Perseverance'],
    keyVerses: ['Jude 1:3', 'Jude 1:24-25'],
  },
  Revelation: {
    author: 'The Apostle John',
    date: 'c. 95 AD (during the reign of Domitian)',
    audience: 'Seven churches in Asia Minor (Ephesus, Smyrna, Pergamos, Thyatira, Sardis, Philadelphia, Laodicea) facing intense persecution.',
    purpose: 'A prophetic vision of Christ\'s ultimate triumph, the judgment of evil, and the restoration of all things. To encourage suffering Christians that the King returns and history ends with His glory.',
    themes: ['Christ\'s sovereignty', 'Judgment', 'Tribulation', 'Second Coming', 'New Heaven and New Earth'],
    keyVerses: ['Revelation 1:7-8', 'Revelation 3:20', 'Revelation 19:11-16', 'Revelation 21:1-4', 'Revelation 22:20'],
  },
  Genesis: {
    author: 'Moses (with possible later editorial work)',
    date: 'c. 1446-1406 BC (during the wilderness wanderings)',
    audience: 'Israel — God\'s newly redeemed people, recently delivered from Egypt and being prepared for the Promised Land.',
    purpose: 'To explain origins: of the universe, of humanity, of sin, and of God\'s redemptive plan through the calling of Abraham.',
    themes: ['Creation', 'The Fall', 'God\'s covenant with Abraham', 'God\'s sovereign providence'],
    keyVerses: ['Genesis 1:1', 'Genesis 1:27', 'Genesis 3:15', 'Genesis 12:1-3', 'Genesis 50:20'],
  },
  Exodus: {
    author: 'Moses',
    date: 'c. 1446-1406 BC',
    audience: 'Israel — to establish their identity as God\'s covenant people.',
    purpose: 'To record Israel\'s deliverance from Egyptian slavery, the giving of the Law at Sinai, and the construction of the Tabernacle.',
    themes: ['Redemption', 'God\'s holiness', 'The Law', 'God dwelling with His people'],
    keyVerses: ['Exodus 3:14', 'Exodus 12:13', 'Exodus 14:14', 'Exodus 20:1-17', 'Exodus 33:14'],
  },
  Psalms: {
    author: 'Multiple — David (~73), Asaph, sons of Korah, Solomon, Moses, Heman, Ethan, anonymous',
    date: 'Spanning c. 1400 BC (Moses) to c. 430 BC (post-exile)',
    audience: 'God\'s covenant people in worship — every emotion of the human heart presented to God.',
    purpose: 'The hymnbook of Israel and the church. Teaches us how to pray, lament, praise, and trust in God in every season.',
    themes: ['Praise', 'Lament', 'Trust', 'Repentance', 'Messianic prophecy'],
    keyVerses: ['Psalm 1', 'Psalm 19:1', 'Psalm 23', 'Psalm 51', 'Psalm 91', 'Psalm 119:105', 'Psalm 139:13-14'],
  },
  Proverbs: {
    author: 'Primarily Solomon, with sections by Agur and Lemuel',
    date: 'c. 950-700 BC',
    audience: 'Originally a young man being trained in wisdom; broadly anyone seeking to live wisely under God.',
    purpose: 'To teach practical wisdom for daily life — the application of fearing God to every area of human existence.',
    themes: ['The fear of the Lord', 'Wisdom vs. folly', 'Speech', 'Diligence', 'Family life'],
    keyVerses: ['Proverbs 1:7', 'Proverbs 3:5-6', 'Proverbs 9:10', 'Proverbs 22:6'],
  },
  Isaiah: {
    author: 'The Prophet Isaiah',
    date: 'c. 740-680 BC',
    audience: 'Judah — facing the Assyrian threat and predicted future Babylonian exile.',
    purpose: 'To proclaim God\'s judgment on sin, His promise of a coming Messiah/Suffering Servant, and the ultimate restoration of His people.',
    themes: ['Holiness of God', 'Coming Messiah', 'Suffering Servant', 'God\'s sovereignty over nations', 'New heavens and new earth'],
    keyVerses: ['Isaiah 6:1-8', 'Isaiah 7:14', 'Isaiah 9:6', 'Isaiah 40:31', 'Isaiah 53', 'Isaiah 55:8-9'],
  },
  Matthew: {
    author: 'Matthew (Levi) — former tax collector, one of the twelve apostles',
    date: 'c. 50-70 AD',
    audience: 'Jewish Christians — Matthew presents Jesus as the long-awaited Messiah and King of Israel.',
    purpose: 'To prove Jesus is the Messiah by emphasizing fulfillment of Old Testament prophecy. Most quoted-from-OT Gospel.',
    themes: ['Jesus as Messiah/King', 'Kingdom of heaven', 'Fulfilled prophecy', 'Discipleship'],
    keyVerses: ['Matthew 1:21-23', 'Matthew 5:3-12', 'Matthew 16:16', 'Matthew 28:18-20'],
  },
  Mark: {
    author: 'John Mark — companion of Peter and Paul',
    date: 'c. 50s-60s AD (likely the earliest Gospel)',
    audience: 'Roman Christians — Mark explains Jewish customs, suggesting Gentile readers.',
    purpose: 'To present Jesus as the Suffering Servant of God — fast-paced, action-focused, with emphasis on what Jesus did over what he taught.',
    themes: ['Jesus as Suffering Servant', 'Discipleship', 'The cross'],
    keyVerses: ['Mark 1:1', 'Mark 8:34-35', 'Mark 10:45', 'Mark 16:15'],
  },
  Luke: {
    author: 'Luke — physician and traveling companion of Paul',
    date: 'c. 60-62 AD',
    audience: '"Most excellent Theophilus" — likely a Roman official; broadly, Greek/Gentile readers.',
    purpose: 'To present an orderly, historically careful account of Jesus as the perfect Son of Man — Savior of all peoples.',
    themes: ['Jesus as Son of Man', 'Salvation for all', 'Compassion for the marginalized', 'Prayer', 'Holy Spirit'],
    keyVerses: ['Luke 1:1-4', 'Luke 2:10-14', 'Luke 4:18-19', 'Luke 19:10', 'Luke 24:46-47'],
  },
  John: {
    author: 'The Apostle John',
    date: 'c. 85-95 AD',
    audience: 'Universal — both believers (to deepen faith) and unbelievers (to bring them to faith).',
    purpose: 'To prove that Jesus is the Christ, the Son of God, and that by believing in him we may have life in his name (John 20:31).',
    themes: ['Deity of Christ', 'Belief and unbelief', 'Eternal life', 'The "I AM" sayings', 'Light and darkness'],
    keyVerses: ['John 1:1-14', 'John 3:16', 'John 10:10', 'John 14:6', 'John 20:31'],
  },
  Acts: {
    author: 'Luke',
    date: 'c. 62-64 AD',
    audience: 'Theophilus and the broader early church.',
    purpose: 'To narrate the spread of the Gospel from Jerusalem to Rome through the work of the Holy Spirit and the apostles, especially Peter and Paul.',
    themes: ['Holy Spirit\'s power', 'Witness and mission', 'The growing church', 'Jew and Gentile'],
    keyVerses: ['Acts 1:8', 'Acts 2:38', 'Acts 4:12', 'Acts 17:11'],
  },
};
