// Extended Did You Know? encyclopedia entries.
// Each entry slots into the existing categories by `category` key.

export const EXTRA_ENTRIES = {
  "Manuscripts & Texts": [
    {
      title: "The Bodmer Papyri",
      year: "c. 175–225 AD",
      location: "Pabau, Egypt",
      tag: "Manuscript",
      summary: "A collection of 22 papyri including some of the earliest copies of Luke and John, dated within ~100 years of the originals.",
      detail: "Discovered in 1952 in Egypt, the Bodmer Papyri include P66 (a near-complete copy of John from c. 200 AD) and P75 (containing most of Luke and John from c. 175–225 AD). P75 is so similar to the 4th-century Codex Vaticanus that it overturned theories that the New Testament text was substantially altered before Constantine. Currently held at the Bibliotheca Bodmeriana in Switzerland and at the Vatican.",
      verse: "Luke 1:3 — 'It seemed good to me also, having had perfect understanding of all things from the very first, to write unto thee in order, most excellent Theophilus.'",
    },
    {
      title: "The Chester Beatty Papyri",
      year: "c. 200–250 AD",
      location: "Egypt",
      tag: "Manuscript",
      summary: "Eleven codices containing portions of the Old and New Testaments, including P46 — the earliest near-complete copy of Paul's epistles.",
      detail: "Acquired by mining magnate Alfred Chester Beatty in the 1930s, these papyri are roughly 100 years older than Codex Sinaiticus. P45 contains portions of all four Gospels and Acts; P46 contains nearly all of Paul's letters. Together they prove the New Testament canon was largely settled and circulating widely by the early 3rd century. Most are housed at the Chester Beatty Library in Dublin.",
      verse: "2 Peter 3:15-16 — 'Our beloved brother Paul also wrote to you... in all his letters...'",
    },
    {
      title: "Codex Vaticanus",
      year: "c. 300–325 AD",
      location: "Vatican Library, Rome",
      tag: "Manuscript",
      summary: "One of the oldest extant complete copies of the Greek Bible, alongside Codex Sinaiticus — the foundation of nearly every modern critical edition of the New Testament.",
      detail: "Vaticanus has been in the Vatican Library since at least 1475. Written in elegant uncial Greek on fine vellum, it contains nearly all the Old and New Testaments. Its text is so close to that of P75 (a century older) that scholars consider it one of the most reliable witnesses to the original New Testament text. It and Codex Sinaiticus together anchor every modern Bible translation.",
      verse: "John 1:1 — 'In the beginning was the Word, and the Word was with God, and the Word was God.'",
    },
    {
      title: "Codex Alexandrinus",
      year: "c. 400–440 AD",
      location: "British Library, London",
      tag: "Manuscript",
      summary: "A 5th-century Greek Bible, one of the four great uncial codices, gifted to King Charles I in 1627.",
      detail: "Codex Alexandrinus contains most of the Greek Old Testament (Septuagint) and most of the New Testament. It was a major manuscript witness used in the first published Greek New Testament critical apparatus. Its presence in England spurred British biblical scholarship in the 17th–19th centuries. Now held at the British Library.",
      verse: "Hebrews 4:12 — 'For the word of God is quick, and powerful, and sharper than any twoedged sword.'",
    },
    {
      title: "The Aleppo Codex",
      year: "c. 920 AD",
      location: "Tiberias, Israel",
      tag: "Manuscript",
      summary: "The most authoritative Hebrew Masoretic Old Testament manuscript ever produced, used by Maimonides as his standard text.",
      detail: "Written by the master scribe Shlomo ben Buya'a and vocalized by Aaron ben Asher in Tiberias around 920 AD, the Aleppo Codex was Maimonides' personal reference and considered the gold standard of the Masoretic tradition. About 60% survives today; portions were lost in a 1947 synagogue fire. It is the foundation of the Hebrew University Bible Project.",
      verse: "Psalm 119:89 — 'For ever, O Lord, thy word is settled in heaven.'",
    },
    {
      title: "The Leningrad Codex",
      year: "1008 AD",
      location: "Saint Petersburg, Russia",
      tag: "Manuscript",
      summary: "The oldest complete Hebrew Bible in existence — basis for nearly every modern Old Testament translation.",
      detail: "Copied in Cairo from the same Ben Asher tradition as the Aleppo Codex, the Leningrad Codex (Codex Leningradensis) is the most complete Masoretic Text of the Hebrew Bible. It is the source text for the Biblia Hebraica Stuttgartensia, which underlies essentially every modern Christian Old Testament translation. Held at the National Library of Russia.",
      verse: "Isaiah 40:8 — 'The grass withereth, the flower fadeth: but the word of our God shall stand for ever.'",
    },
    {
      title: "The Magdalen Papyrus (P64)",
      year: "c. 200 AD (some scholars: 1st century)",
      location: "Luxor, Egypt",
      tag: "Manuscript",
      summary: "Three small fragments of Matthew's Gospel discovered at Luxor — once controversially dated to the mid-1st century.",
      detail: "Acquired in 1901 by Magdalen College, Oxford, P64 contains parts of Matthew 26. Most paleographers date it to ~200 AD, but Carsten Thiede argued in 1994 for a 1st-century date — which would put it within living memory of Jesus. The mainstream date still places it among the earliest Matthew witnesses we possess.",
      verse: "Matthew 26:23 — 'He that dippeth his hand with me in the dish, the same shall betray me.'",
    },
    {
      title: "Papyrus 4 (P4)",
      year: "c. 175–250 AD",
      location: "Coptos, Egypt",
      tag: "Manuscript",
      summary: "An early papyrus copy of Luke's Gospel, one of the earliest known Luke witnesses.",
      detail: "Discovered in a wall jar at Coptos in 1889 along with binding materials of a 3rd-century codex, P4 contains portions of Luke 1, 2, 3, 4, 5, and 6. Its text agrees closely with the later Codex Vaticanus — strong evidence that the gospel text we have today is the same text that was circulating before Constantine.",
      verse: "Luke 2:11 — 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.'",
    },
    {
      title: "The Septuagint (LXX)",
      year: "c. 250–100 BC",
      location: "Alexandria, Egypt",
      tag: "Manuscript",
      summary: "The Greek translation of the Hebrew Old Testament — the Bible used by Jesus and the apostles, predating the New Testament.",
      detail: "Tradition holds that 70 (or 72) Jewish scholars in Alexandria translated the Torah into Greek for the Library of Alexandria around 250 BC, with the rest of the Old Testament translated over the following centuries. Most New Testament Old Testament quotations follow the Septuagint, and many early Christians knew the Old Testament only in Greek. Surviving Septuagint manuscripts include Codex Vaticanus and Sinaiticus.",
      verse: "Acts 8:32-33 — The Ethiopian eunuch reads from Isaiah in the Septuagint.",
    },
    {
      title: "Codex Bezae",
      year: "c. 400 AD",
      location: "Cambridge University Library",
      tag: "Manuscript",
      summary: "A bilingual Greek-Latin manuscript of the Gospels and Acts, named after Reformer Theodore Beza who gave it to Cambridge in 1581.",
      detail: "Codex Bezae presents the four Gospels in the 'Western' order (Matthew, John, Luke, Mark) with Greek and Latin on facing pages. Its text of Acts is roughly 10% longer than the standard text, with additional details that scholars debate may preserve genuine early traditions. It is one of the most studied 'Western text-type' manuscripts.",
      verse: "Acts 1:1 — 'The former treatise have I made, O Theophilus, of all that Jesus began both to do and teach.'",
    },
    {
      title: "Papyrus 46 (P46)",
      year: "c. 175–225 AD",
      location: "Egypt (now Michigan & Dublin)",
      tag: "Manuscript",
      summary: "The earliest near-complete manuscript of Paul's letters, predating other major witnesses by over 100 years.",
      detail: "P46 contains most of Romans, Hebrews, 1–2 Corinthians, Ephesians, Galatians, Philippians, Colossians, and 1 Thessalonians. Its existence at the end of the 2nd century proves Paul's letters were already collected and circulated as a unit — and that Hebrews was associated with the Pauline corpus from the earliest days. Pages are split between the University of Michigan and the Chester Beatty Library.",
      verse: "Romans 1:16 — 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation.'",
    },
    {
      title: "Codex Washingtonianus",
      year: "c. 400 AD",
      location: "Smithsonian, Washington DC",
      tag: "Manuscript",
      summary: "A 4th–5th century Greek manuscript of the four Gospels, notable for the unique 'Freer Logion' addition to Mark.",
      detail: "Acquired by Charles Lang Freer in Egypt in 1906, this codex includes a unique additional saying of Jesus inserted into Mark 16. Its mixed textual character — Western in Mark, Alexandrian in Luke, Byzantine in Matthew — gives it a special place in textual criticism.",
      verse: "Mark 16:15 — 'Go ye into all the world, and preach the gospel to every creature.'",
    },
    {
      title: "The Lindisfarne Gospels",
      year: "c. 700 AD",
      location: "Lindisfarne, England",
      tag: "Manuscript",
      summary: "An exquisitely illuminated Latin Gospel manuscript produced by monks on Holy Island — a masterpiece of Insular art.",
      detail: "Created by monk Eadfrith of Lindisfarne, the Lindisfarne Gospels combine Celtic, Anglo-Saxon, and Mediterranean artistic traditions. A 10th-century scribe added a word-by-word Old English gloss — the oldest surviving English translation of the Gospels. Now in the British Library.",
      verse: "Matthew 28:20 — 'Lo, I am with you alway, even unto the end of the world.'",
    },
    {
      title: "Tyndale's English New Testament",
      year: "1526",
      location: "Worms, Germany",
      tag: "Manuscript",
      summary: "The first New Testament printed in English from the original Greek — William Tyndale was burned at the stake for producing it.",
      detail: "Tyndale fled England to translate and print the New Testament from Erasmus's Greek text. His phrasing — 'Let there be light,' 'the powers that be,' 'salt of the earth,' 'fight the good fight' — directly shaped the King James Version (which used about 83% of his New Testament wording). He was strangled and burned in 1536. His final prayer: 'Lord, open the King of England's eyes.' Three years later, Henry VIII authorized the English Bible.",
      verse: "John 1:1 — 'In the beginnynge was the worde, and the worde was with God: and the worde was God.' (Tyndale 1526)",
    },
    {
      title: "The Great Isaiah Scroll",
      year: "c. 125 BC",
      location: "Qumran Cave 1, Israel",
      tag: "Manuscript",
      summary: "A complete copy of the book of Isaiah found among the Dead Sea Scrolls — 1,000 years older than any previously known Hebrew copy.",
      detail: "When unrolled, the Great Isaiah Scroll (1QIsaa) measures 24 feet long and contains all 66 chapters of Isaiah on 17 sheets of leather. When compared to the Masoretic Text from 1,000 years later, the two are essentially identical — a stunning testament to the precision of Jewish scribal tradition. The scroll is on display at the Shrine of the Book in Jerusalem.",
      verse: "Isaiah 53:5 — 'But he was wounded for our transgressions, he was bruised for our iniquities...'",
    },
  ],

  "Archaeological Discoveries": [
    {
      title: "The Caiaphas Ossuary",
      year: "Discovered 1990",
      location: "Jerusalem",
      tag: "Artifact",
      summary: "An ornately decorated 1st-century bone box inscribed 'Joseph son of Caiaphas' — likely the high priest who tried Jesus.",
      detail: "Found accidentally during construction of a water park in the Peace Forest of Jerusalem, this ossuary contains the bones of an elderly man and bears the Aramaic inscription 'Yehosef bar Qayafa.' Josephus identifies the high priest who presided over Jesus's trial as 'Joseph who is called Caiaphas.' This is the only physical artifact identified with a person who personally interrogated Jesus. Now at the Israel Museum.",
      verse: "Matthew 26:57 — 'They led him away to Caiaphas the high priest...'",
    },
    {
      title: "The Erastus Inscription",
      year: "c. 50–80 AD",
      location: "Corinth, Greece",
      tag: "Inscription",
      summary: "A pavement inscription naming 'Erastus, in return for his aedileship, laid this pavement at his own expense' — likely Paul's friend Erastus.",
      detail: "Discovered in 1929 in front of the theater at ancient Corinth, this Latin inscription records that an aedile (city official) named Erastus paved a section of the city. Romans 16:23, written from Corinth, sends greetings from 'Erastus, the chamberlain (city treasurer) of the city.' Most scholars accept this as the same person — directly tying a New Testament figure to a physical inscription.",
      verse: "Romans 16:23 — 'Erastus the chamberlain of the city saluteth you, and Quartus a brother.'",
    },
    {
      title: "The Megiddo Church Mosaic",
      year: "c. 230 AD",
      location: "Megiddo, Israel",
      tag: "Structure",
      summary: "The oldest known Christian church mosaic, with an inscription referring to 'God Jesus Christ' — predating the Council of Nicaea by nearly a century.",
      detail: "Discovered in 2005 during prison construction at Megiddo, this mosaic floor of a 3rd-century house church contains a Greek inscription: 'The God-loving Akeptous has offered the table to God Jesus Christ as a memorial.' This phrase — naming Jesus as God in a Christian inscription dated before Constantine — directly contradicts the Dan-Brown-style myth that Jesus's deity was invented at Nicaea in 325 AD.",
      verse: "Titus 2:13 — 'Looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ.'",
    },
    {
      title: "The Ophel Treasure",
      year: "c. 7th century AD (artifacts much older)",
      location: "Jerusalem, Israel",
      tag: "Artifact",
      summary: "A hoard of 36 Byzantine gold coins and a gold medallion engraved with a menorah, shofar, and Torah scroll — found near the Temple Mount.",
      detail: "Excavated by Eilat Mazar in 2013 just south of the Temple Mount, the Ophel Treasure includes a 10-cm gold medallion etched with a seven-branched menorah, a shofar, and a Torah scroll — the oldest known Torah scroll depiction on a Jewish artifact. The cache was likely abandoned during the Persian conquest of Jerusalem in 614 AD. It demonstrates continuous Jewish presence and religious practice in Jerusalem.",
      verse: "Psalm 137:5-6 — 'If I forget thee, O Jerusalem, let my right hand forget her cunning.'",
    },
    {
      title: "Hezekiah's Bulla",
      year: "c. 700 BC",
      location: "Jerusalem, Israel",
      tag: "Artifact",
      summary: "A clay seal impression bearing the words 'Belonging to Hezekiah, [son of] Ahaz, king of Judah' — the first king's seal found in scientific excavation in Israel.",
      detail: "Discovered in 2009 during Eilat Mazar's excavations near the Temple Mount and identified in 2015, this bulla bears the impression of King Hezekiah's personal seal. The seal shows a two-winged sun disk and ankh symbols flanking the inscription. It is direct physical evidence of a biblical king who reigned 715–686 BC and is mentioned in 2 Kings, 2 Chronicles, and Isaiah.",
      verse: "2 Kings 18:5 — 'He trusted in the Lord God of Israel; so that after him was none like him among all the kings of Judah.'",
    },
    {
      title: "Isaiah's Bulla",
      year: "c. 700 BC",
      location: "Jerusalem, Israel",
      tag: "Artifact",
      summary: "A clay seal impression possibly belonging to the prophet Isaiah, found just feet from Hezekiah's bulla.",
      detail: "Found in the same Eilat Mazar excavation as the Hezekiah bulla and announced in 2018, this damaged seal reads '...belonging to Yesha'yahu (Isaiah)' followed by characters that may spell 'nvy' — possibly the Hebrew word for 'prophet.' If correct, this would be the first archaeological evidence of the prophet Isaiah. Its proximity to Hezekiah's seal matches the biblical record of their close relationship.",
      verse: "2 Kings 19:20 — 'Then Isaiah the son of Amoz sent to Hezekiah, saying, Thus saith the Lord God of Israel...'",
    },
    {
      title: "The Lachish Letters",
      year: "c. 588 BC",
      location: "Lachish, Israel",
      tag: "Inscription",
      summary: "Pottery shards inscribed with military dispatches written days before Babylon destroyed the city — corroborating the biblical fall of Judah.",
      detail: "Discovered in 1935 in the burnt remains of a guard room at Lachish, these 21 ostraca (inscribed pottery fragments) were urgent letters written in ancient Hebrew. Letter IV mentions watching for fire signals from Lachish but no longer seeing them from Azekah — exactly the situation described in Jeremiah 34:7, where Lachish and Azekah are the last remaining Judean cities before Jerusalem fell. The letters are now in the British Museum and Israel Museum.",
      verse: "Jeremiah 34:7 — 'When the king of Babylon's army fought against Jerusalem...against Lachish, and against Azekah: for these defenced cities remained of the cities of Judah.'",
    },
    {
      title: "The Ekron Inscription",
      year: "c. 700 BC",
      location: "Tel Miqne (biblical Ekron), Israel",
      tag: "Inscription",
      summary: "A royal dedication stone naming five Philistine kings — the first physical inscription confirming the biblical Philistine pentapolis.",
      detail: "Found in 1996 at Tel Miqne, this limestone block was a temple dedication by 'Ikausu son of Padi son of Ysd son of Ada son of Ya'ir, ruler of Ekron.' The Bible mentions Padi, king of Ekron, in connection with Hezekiah's reign (2 Kings 18). The inscription confirms the existence of Ekron as a Philistine royal city exactly as described in Joshua, Samuel, and Kings.",
      verse: "1 Samuel 5:10 — 'Therefore they sent the ark of God to Ekron.'",
    },
    {
      title: "Sennacherib's Prism",
      year: "c. 690 BC",
      location: "Nineveh (modern Iraq)",
      tag: "Inscription",
      summary: "A six-sided clay prism on which the Assyrian king Sennacherib boasts of besieging Hezekiah 'like a bird in a cage' — but tellingly never claims to capture Jerusalem.",
      detail: "Discovered in 1830 by Colonel Robert Taylor (the 'Taylor Prism'), this is one of three nearly identical prisms (others at the Oriental Institute and Israel Museum). Sennacherib lists his conquests in detail, including the destruction of 46 fortified Judean cities. He confines Hezekiah 'in his royal city, like a caged bird' — but never takes the city. This silence corroborates the biblical account of God's miraculous deliverance of Jerusalem (2 Kings 19, Isaiah 37).",
      verse: "Isaiah 37:36 — 'Then the angel of the Lord went forth, and smote in the camp of the Assyrians a hundred and fourscore and five thousand.'",
    },
    {
      title: "The Black Obelisk of Shalmaneser III",
      year: "c. 825 BC",
      location: "Nimrud (modern Iraq)",
      tag: "Inscription",
      summary: "An Assyrian monument depicting King Jehu of Israel bowing before Shalmaneser III — the only known portrait of an Israelite king.",
      detail: "Discovered by Austen Henry Layard in 1846 at Nimrud, this 6.5-foot black limestone obelisk includes a relief panel labeled 'tribute of Jehu, son of Omri.' It shows an Israelite figure prostrate before the Assyrian king. This is the earliest depiction of an Israelite ever found and confirms Jehu's reign (841–814 BC) as recorded in 2 Kings 9–10. Now at the British Museum.",
      verse: "2 Kings 10:32 — 'In those days the Lord began to cut Israel short.'",
    },
    {
      title: "The Pool of Bethesda",
      year: "Discovered 1888",
      location: "Jerusalem, Israel",
      tag: "Structure",
      summary: "A twin-pool complex with five porticoes excavated in Jerusalem — exactly matching John 5's description of where Jesus healed the lame man.",
      detail: "Critics long argued that John 5's 'pool with five porches' was symbolic, since no such pool was known. Excavations near the Church of St. Anne in the late 1800s and through the 20th century uncovered a large twin-pool complex surrounded by colonnades on four sides plus one between the pools — totaling five. The detailed knowledge of Jerusalem's geography in the Gospel of John, written near the end of the 1st century, points to an eyewitness source.",
      verse: "John 5:2 — 'Now there is at Jerusalem by the sheep market a pool, which is called in the Hebrew tongue Bethesda, having five porches.'",
    },
    {
      title: "The Synagogue at Capernaum",
      year: "1st century synagogue beneath 4th century structure",
      location: "Capernaum, Israel",
      tag: "Structure",
      summary: "Beneath the imposing 4th-century synagogue at Capernaum lie the basalt foundations of the 1st-century synagogue where Jesus taught.",
      detail: "Excavations beneath the visible white limestone synagogue revealed black basalt walls of a 1st-century building of the same dimensions. Mark 1:21 records Jesus teaching here and casting out a demon. Nearby is a 1st-century house identified since the 4th century as Peter's house, with graffiti naming Christ. The synagogue and Peter's house are visible to visitors today.",
      verse: "Luke 4:31 — 'And came down to Capernaum, a city of Galilee, and taught them on the sabbath days.'",
    },
    {
      title: "The House of Peter at Capernaum",
      year: "1st century BC house, venerated since 1st century AD",
      location: "Capernaum, Israel",
      tag: "Structure",
      summary: "An early 1st-century house plastered and decorated as a Christian gathering place by the late 1st century — long identified as Peter's home.",
      detail: "Discovered by Franciscan archaeologists, this small house was modified in the late 1st century: walls plastered, no domestic objects, Christian graffiti added (including 'Lord Jesus Christ help your servant'). By the 4th century it was enclosed in a church. The 4th-century pilgrim Egeria described it as the home of Peter where Jesus stayed. Mark 1:29 places Jesus's Capernaum activity at Peter's house.",
      verse: "Mark 1:29 — 'They entered into the house of Simon and Andrew, with James and John.'",
    },
    {
      title: "The Crucified Heel Bone",
      year: "1st century AD",
      location: "Giv'at HaMivtar, Jerusalem",
      tag: "Artifact",
      summary: "A heel bone with an iron crucifixion nail still embedded — the only physical evidence of Roman crucifixion ever recovered.",
      detail: "Found in 1968 in a Jewish ossuary, the heel bone of 'Yehohanan ben Hagkol' contained a 4.5-inch iron nail bent at the tip — explaining why nails were rarely recovered (they were difficult to extract). The discovery proved that the Romans really did crucify with nails through the heels (not just ropes), confirming the Gospel accounts. The man was crucified around the same period as Jesus.",
      verse: "John 20:25 — 'Except I shall see in his hands the print of the nails, and put my finger into the print of the nails...'",
    },
    {
      title: "The Magdala Stone",
      year: "1st century AD",
      location: "Magdala, Sea of Galilee",
      tag: "Artifact",
      summary: "A carved limestone block from a 1st-century synagogue depicting a seven-branched menorah from before the Temple's destruction.",
      detail: "Found in 2009 in the synagogue at Magdala (hometown of Mary Magdalene), this stone is the earliest known artistic representation of the Jerusalem Temple's menorah, carved by someone who likely had seen it firsthand. The synagogue itself is one of only seven 1st-century synagogues ever found in Israel, and Jesus almost certainly taught in it (Matthew 4:23).",
      verse: "Luke 8:1-2 — 'Mary called Magdalene, out of whom went seven devils...'",
    },
    {
      title: "The Sergius Paulus Inscription",
      year: "1st century AD",
      location: "Cyprus and Pisidian Antioch",
      tag: "Inscription",
      summary: "Inscriptions from Cyprus and Pisidian Antioch confirm a Roman official named Sergius Paulus — exactly the proconsul converted by Paul in Acts 13.",
      detail: "Acts 13:6-12 describes Paul converting 'Sergius Paulus, a prudent man,' the proconsul of Cyprus. Multiple inscriptions found at Soli on Cyprus and Pisidian Antioch in modern Turkey name 'Lucius Sergius Paulus' as a Roman official. The Antioch inscription suggests his family origin there — explaining why Paul's missionary route turned north into the Sergius Paulus family region after Cyprus.",
      verse: "Acts 13:7 — 'Which was with the deputy of the country, Sergius Paulus, a prudent man.'",
    },
    {
      title: "The Politarch Inscription",
      year: "1st–2nd century AD",
      location: "Thessalonica, Greece",
      tag: "Inscription",
      summary: "A Roman arch inscription using the rare Greek title 'politarch' — the same title Luke uses in Acts 17 — vindicating his historical accuracy.",
      detail: "For centuries critics ridiculed Luke for calling Thessalonican rulers 'politarchs' (Acts 17:6, 8) since the title was unknown anywhere else in Greek literature. Then 19th-century inscriptions on the Vardar Gate in Thessalonica and elsewhere revealed politarch was indeed the local technical term for the city magistrates. Sir William Ramsay called this proof of Luke's status as 'a historian of the first rank.'",
      verse: "Acts 17:6 — 'They drew Jason and certain brethren unto the rulers of the city (politarchs).'",
    },
    {
      title: "The Gallio Inscription",
      year: "c. 52 AD",
      location: "Delphi, Greece",
      tag: "Inscription",
      summary: "A Greek inscription naming Gallio as proconsul of Achaia — providing one of the most precise dates anchoring New Testament chronology.",
      detail: "This inscription contains a letter from Emperor Claudius dated 52 AD that mentions 'L. Junius Gallio, my friend and proconsul.' Acts 18:12-17 places Paul before this same Gallio in Corinth. Since Roman proconsular terms were typically one year, Paul's appearance in Corinth can be dated to ~51 AD — making this one of the most precisely datable events in the New Testament.",
      verse: "Acts 18:12 — 'When Gallio was the deputy of Achaia, the Jews made insurrection with one accord against Paul.'",
    },
    {
      title: "The Theodotus Inscription",
      year: "1st century AD (before 70)",
      location: "Jerusalem, Israel",
      tag: "Inscription",
      summary: "A Greek synagogue dedication stone confirming Greek-speaking synagogues operated in Jerusalem during Jesus's lifetime.",
      detail: "Found in a cistern on the Ophel south of the Temple Mount in 1913, this stone records the dedication of a synagogue 'for the reading of the Law and the teaching of the commandments' by Theodotus, son of Vettenus, a priest. It confirms Acts 6:9 mentions of Greek-speaking 'Synagogue of the Freedmen' in Jerusalem. Now in the Israel Museum.",
      verse: "Acts 6:9 — 'There arose certain of the synagogue, which is called the synagogue of the Libertines.'",
    },
    {
      title: "The Burnt House",
      year: "Destroyed 70 AD",
      location: "Jerusalem, Israel",
      tag: "Structure",
      summary: "A wealthy priestly home in Jerusalem's Upper City frozen in time the day Romans burned it — including a stone weight of the priestly Bar-Kathros family known from the Talmud.",
      detail: "Excavated in the 1970s, the Burnt House was incinerated when Romans destroyed Jerusalem in 70 AD. Inside were stone vessels (used by priests for ritual purity), coins of the Jewish revolt, an iron spear, the bones of an arm reaching for a step, and a stone weight inscribed 'son of Kathros.' The Babylonian Talmud preserves a poem cursing the corrupt Bar-Kathros priestly family. Now an underground museum.",
      verse: "Luke 21:6 — 'As for these things which ye behold, the days will come, in the which there shall not be left one stone upon another.'",
    },
    {
      title: "Robinson's Arch",
      year: "1st century BC",
      location: "Jerusalem, Israel",
      tag: "Structure",
      summary: "The remains of a monumental staircase that ascended to the Herodian Temple Mount — the same one Jesus and the apostles climbed.",
      detail: "Named after biblical scholar Edward Robinson who identified it in 1838, this arch springer projects from the Western Wall. It once supported a grand staircase that brought worshippers up from the main shopping street into the Royal Stoa on the Temple platform. Below, archaeologists found massive stones thrown down by the Romans in 70 AD — a vivid fulfillment of Jesus's prophecy that 'not one stone shall be left upon another.'",
      verse: "Mark 13:1-2 — 'Master, see what manner of stones and what buildings are here!...there shall not be left one stone upon another.'",
    },
    {
      title: "The Trumpeting Stone",
      year: "1st century AD",
      location: "Jerusalem, Israel",
      tag: "Inscription",
      summary: "A monumental stone from the parapet of the Herodian Temple inscribed 'to the place of trumpeting.'",
      detail: "Found in 1969 in the rubble at the southwest corner of the Temple Mount, this large block bears an unfinished Hebrew inscription: 'To the trumpeting place to dec[lare].' It marked where a priest stood to blow a silver trumpet announcing the start of the Sabbath. Josephus describes this exact position. Now at the Israel Museum.",
      verse: "Numbers 10:10 — 'In the day of your gladness... ye shall blow with the trumpets over your burnt offerings.'",
    },
    {
      title: "The Cardo Maximus",
      year: "6th century AD on 1st century foundation",
      location: "Jerusalem, Israel",
      tag: "Structure",
      summary: "The colonnaded main street of Roman Jerusalem, depicted on the 6th century Madaba Map and visible today in the Jewish Quarter.",
      detail: "Excavated in the 1970s–80s, the Cardo Maximus was Jerusalem's main north-south boulevard during the Roman and Byzantine periods. Lined with massive columns and shops, it appears on the famous Madaba mosaic map of Jerusalem (c. 560 AD). A reconstructed section is open to visitors in the Old City.",
      verse: "Psalm 122:2 — 'Our feet shall stand within thy gates, O Jerusalem.'",
    },
    {
      title: "The Madaba Map",
      year: "c. 560 AD",
      location: "Madaba, Jordan",
      tag: "Inscription",
      summary: "The oldest surviving cartographic depiction of Jerusalem and the Holy Land — preserved in a 6th-century church mosaic floor.",
      detail: "Discovered in 1884 in the floor of St. George's Church in Madaba, this 6×16 meter Byzantine mosaic map shows over 150 sites in the Holy Land labeled in Greek. The detailed plan of Jerusalem includes the Cardo, the Damascus Gate, and the Church of the Holy Sepulchre — many features confirmed by modern excavation. It is the oldest surviving original cartographic depiction of the Holy Land.",
      verse: "Psalm 87:1-2 — 'His foundation is in the holy mountains. The Lord loveth the gates of Zion.'",
    },
  ],

  "Historical Confirmations": [
    {
      title: "Suetonius on Christ in Rome",
      year: "c. 121 AD",
      location: "Rome",
      tag: "Historical Record",
      summary: "Roman historian Suetonius records Emperor Claudius expelling Jews from Rome 'because they constantly made disturbances at the instigation of Chrestus.'",
      detail: "In his 'Lives of the Twelve Caesars' (c. 121 AD), Suetonius writes that Claudius (41–54 AD) banished Jews from Rome over disputes about 'Chrestus' — most scholars agree this is a misspelling of 'Christ.' Acts 18:2 records the same expulsion: Paul met Aquila and Priscilla in Corinth because 'Claudius had commanded all Jews to depart from Rome.' This is independent confirmation that Christianity had reached Rome and was already causing controversy by ~49 AD.",
      verse: "Acts 18:2 — 'Claudius had commanded all Jews to depart from Rome.'",
    },
    {
      title: "Mara bar Serapion's Letter",
      year: "c. 73 AD or later",
      location: "Syria (held in British Museum)",
      tag: "Historical Record",
      summary: "A Syrian Stoic philosopher writing to his son refers to the Jews killing their 'wise King' — likely a non-Christian reference to Jesus.",
      detail: "This letter from Mara bar Serapion compares the deaths of Socrates, Pythagoras, and the 'wise King' of the Jews. Mara writes: 'Nor did the wise King die for good; He lived on in the teaching which He had given.' The reference to the destruction of the Jews shortly after killing this king strongly implies Jesus, since Jerusalem fell in 70 AD. Notable as a non-Christian, non-Jewish, and non-Roman source.",
      verse: "John 1:11 — 'He came unto his own, and his own received him not.'",
    },
    {
      title: "Lucian of Samosata on Christians",
      year: "c. 165 AD",
      location: "Syria",
      tag: "Historical Record",
      summary: "A pagan satirist mocks Christians for worshipping a 'crucified sage' and treating each other as brothers — accidentally confirming the historical Jesus.",
      detail: "In 'The Death of Peregrine,' Lucian writes: 'The Christians, you know, worship a man to this day — the distinguished personage who introduced their novel rites, and was crucified on that account... they worship the crucified sage and live after his laws.' Lucian's mocking tone makes the testimony all the more valuable — he confirms Jesus existed, was crucified, and his followers continued to honor him as a teacher, all without intending to support Christianity.",
      verse: "1 Corinthians 1:23 — 'But we preach Christ crucified, unto the Jews a stumblingblock, and unto the Greeks foolishness.'",
    },
    {
      title: "The Babylonian Talmud on Jesus",
      year: "Compiled c. 200–500 AD",
      location: "Babylonia",
      tag: "Historical Record",
      summary: "Hostile Jewish references in the Babylonian Talmud confirm Jesus's existence, his crucifixion 'on the eve of Passover,' and his miracles (interpreted as sorcery).",
      detail: "Sanhedrin 43a says: 'On the eve of Passover, Yeshu was hanged. For forty days before the execution took place, a herald... cried, He is going forth to be stoned because he has practiced sorcery and enticed Israel to apostasy.' The reference to crucifixion ('hanged') on the eve of Passover, the charge of working signs ('sorcery'), and his ability to attract followers all align with the Gospel accounts — given by hostile witnesses with no motive to corroborate Christian claims.",
      verse: "Mark 15:42-46 — 'And now when the even was come, because it was the preparation, that is, the day before the sabbath...'",
    },
    {
      title: "Thallus on the Darkness at the Crucifixion",
      year: "c. 52 AD",
      location: "Mediterranean",
      tag: "Historical Record",
      summary: "A 1st-century Samaritan historian attempted to explain away the darkness at Jesus's crucifixion as a solar eclipse — confirming the event happened.",
      detail: "Thallus's original work is lost, but Julius Africanus quoted him around 220 AD: 'Thallus, in the third book of his histories, explains away this darkness as an eclipse of the sun — unreasonably, as it seems to me.' (Africanus notes a solar eclipse is impossible during Passover, which always occurs at full moon.) Thallus's attempt to explain a known event proves the darkness at the crucifixion was already widely discussed within ~20 years of the event.",
      verse: "Luke 23:44 — 'It was about the sixth hour, and there was a darkness over all the earth until the ninth hour.'",
    },
    {
      title: "Phlegon of Tralles on the Crucifixion Darkness",
      year: "c. 137 AD",
      location: "Roman Empire",
      tag: "Historical Record",
      summary: "A Greek historian reported a great darkness and earthquake during the reign of Tiberius — corroborating the crucifixion accounts.",
      detail: "Phlegon's original 'Olympiads' is lost, but multiple early Christian writers (Origen, Eusebius, Africanus) quote him as recording 'the greatest eclipse of the sun' and a great earthquake in Bithynia during the 4th year of the 202nd Olympiad — which corresponds to 33 AD. Combined with Thallus and Tertullian's reference to a 'cosmic event recorded in your own archives' (Apologeticum 21), this points to a real, widely-noticed astronomical or atmospheric event matching the Gospel accounts.",
      verse: "Matthew 27:45 — 'Now from the sixth hour there was darkness over all the land unto the ninth hour.'",
    },
    {
      title: "Origen's Reference to Josephus",
      year: "c. 248 AD",
      location: "Caesarea",
      tag: "Historical Record",
      summary: "Early Christian scholar Origen quotes Josephus's reference to 'James, the brother of Jesus called Christ' — confirming this passage is genuine and not a later Christian insertion.",
      detail: "Critics often allege the Josephus references to Jesus were later Christian forgeries. But Origen, writing in 248 AD, twice quotes Josephus's account of James the brother of Jesus — and notably criticizes Josephus for NOT believing Jesus was the Messiah. This proves Origen was reading Josephus's authentic, non-Christian text, and confirms the James passage (Antiquities 20.9.1) is original to Josephus, not a later Christian addition.",
      verse: "Galatians 1:19 — 'But other of the apostles saw I none, save James the Lord's brother.'",
    },
    {
      title: "Eusebius's Ecclesiastical History",
      year: "c. 312–324 AD",
      location: "Caesarea",
      tag: "Historical Record",
      summary: "Eusebius's compilation of early church history preserves quotes from now-lost works of Papias, Hegesippus, and other 2nd-century Christians who knew Jesus's followers personally.",
      detail: "Eusebius quotes Papias (c. 95–120 AD) — who knew the Apostle John and Aristion — about the origins of Mark's Gospel: 'Mark, having been the interpreter of Peter, wrote down accurately, though not in order, all that he remembered of the Lord's sayings and doings.' This direct chain of testimony from John → Papias → Eusebius links the Gospel of Mark to the apostolic eyewitnesses.",
      verse: "1 John 1:1 — 'That which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life.'",
    },
    {
      title: "Polycarp of Smyrna",
      year: "c. 70–155 AD",
      location: "Smyrna, Asia Minor",
      tag: "Historical Record",
      summary: "Bishop Polycarp was personally discipled by the Apostle John and was martyred in his 80s — providing a direct living link between the apostles and the post-apostolic church.",
      detail: "Polycarp was a disciple of the Apostle John and bishop of Smyrna. Irenaeus (who heard Polycarp preach as a young man) records Polycarp recounting personal stories of John and other eyewitnesses of Jesus. At age 86, Polycarp was burned at the stake for refusing to renounce Christ, declaring: 'Eighty and six years have I served Him, and He never did me any wrong. How then can I blaspheme my King and my Saviour?' His Letter to the Philippians survives.",
      verse: "Revelation 2:10 — 'Be thou faithful unto death, and I will give thee a crown of life.'",
    },
    {
      title: "Ignatius of Antioch's Letters",
      year: "c. 107 AD",
      location: "En route from Syria to Rome",
      tag: "Historical Record",
      summary: "Seven letters written by Ignatius on his journey to martyrdom in Rome are among our earliest non-canonical Christian writings — quoting heavily from the Gospels and Paul's letters.",
      detail: "Bishop Ignatius of Antioch was condemned to be killed by wild beasts in Rome's Colosseum around 107 AD. On his journey there, he wrote seven letters to churches he passed through. He quotes or alludes to Matthew, Luke, John, and many of Paul's epistles — proving these texts were already widely accepted as Scripture by the early 2nd century. He also strongly affirms the deity of Christ ('our God Jesus Christ').",
      verse: "Romans 6:13 — 'Yield yourselves unto God, as those that are alive from the dead.'",
    },
    {
      title: "The Didache",
      year: "c. 50–120 AD",
      location: "Syria/Egypt",
      tag: "Historical Record",
      summary: "An early Christian instruction manual quoting extensively from Matthew — possibly contemporary with the New Testament itself.",
      detail: "Discovered in 1873 in Constantinople, the Didache ('Teaching of the Twelve Apostles') gives practical instructions on baptism, the Eucharist, prayer (including the Lord's Prayer in a slightly variant form), and church order. It quotes Matthew extensively, suggesting either Matthew was already in circulation or both shared a common early source. It places communion observance and trinitarian baptism in the very earliest church.",
      verse: "Matthew 28:19 — 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.'",
    },
    {
      title: "Clement of Rome's Letter",
      year: "c. 95 AD",
      location: "Rome",
      tag: "Historical Record",
      summary: "A letter from the church at Rome to the church at Corinth, written within decades of the apostles, quoting Paul's first Corinthian letter.",
      detail: "1 Clement is one of the earliest surviving Christian writings outside the New Testament, written by Clement of Rome around 95 AD. It explicitly references Paul's letter to the Corinthians and quotes from at least 8 books of the New Testament. It also gives us our earliest historical reference to the martyrdoms of Peter and Paul in Rome, locating them under Nero's persecution around 65 AD.",
      verse: "1 Corinthians 1:11 — 'It hath been declared unto me of you, my brethren...'",
    },
    {
      title: "The Edict of Milan",
      year: "313 AD",
      location: "Milan, Italy",
      tag: "Historical Record",
      summary: "Emperor Constantine and co-emperor Licinius issued an edict legalizing Christianity throughout the Roman Empire after centuries of persecution.",
      detail: "The Edict of Milan ended state persecution of Christians and restored church property confiscated during the Diocletianic persecution. Within decades, what had begun as an obscure Galilean movement of fishermen and tax collectors had become the official religion of the Roman Empire — without any military or political backing during its growth period. Historians have long noted this peaceful expansion as remarkable.",
      verse: "Matthew 16:18 — 'Upon this rock I will build my church; and the gates of hell shall not prevail against it.'",
    },
    {
      title: "Ammianus Marcellinus on Jewish Temple",
      year: "c. 380 AD",
      location: "Rome",
      tag: "Historical Record",
      summary: "A 4th-century Roman historian records Emperor Julian's failed attempt to rebuild the Jerusalem Temple — fireballs from the earth stopped the work.",
      detail: "Emperor Julian the Apostate (361–363 AD) tried to rebuild the Jerusalem Temple specifically to disprove Jesus's prophecy that 'not one stone' would remain. The pagan historian Ammianus Marcellinus records: 'Fearful balls of fire breaking out near the foundations, with frequent assaults, rendered the place inaccessible to the workmen, who were repeatedly burned.' The project was abandoned. Christians saw this as confirmation of Christ's prophecy.",
      verse: "Matthew 24:2 — 'Verily I say unto you, There shall not be left here one stone upon another.'",
    },
    {
      title: "The Nag Hammadi Library",
      year: "c. 350 AD (texts written 100–300 AD)",
      location: "Nag Hammadi, Egypt",
      tag: "Manuscript",
      summary: "A buried jar of Gnostic codices discovered in 1945 — illuminating what early Christians rejected as heresy.",
      detail: "A peasant named Muhammad Ali al-Samman discovered 13 leather-bound codices buried in a sealed jar near the Egyptian village of Nag Hammadi. The 52 mostly-Gnostic texts (including the Gospel of Thomas, Gospel of Philip) were written 100–300 AD and deliberately hidden — likely after Athanasius's 367 AD letter listing the canonical New Testament. The discovery confirmed how the early church discerned authentic apostolic writings from later sectarian compositions.",
      verse: "1 John 4:1 — 'Beloved, believe not every spirit, but try the spirits whether they are of God.'",
    },
    {
      title: "The Muratorian Fragment",
      year: "c. 170 AD",
      location: "Italy (now Milan)",
      tag: "Historical Record",
      summary: "The earliest known list of New Testament books — confirming the canon was substantially recognized within decades of the apostles.",
      detail: "Discovered by Italian historian Lodovico Muratori in the 18th century, this fragment lists most of our current New Testament as authoritative scripture by 170 AD: the four Gospels, Acts, 13 letters of Paul, Jude, 1 and 2 John, and Revelation. It also explicitly rejects pseudepigraphical works like the 'Letter to the Laodiceans.' The list demonstrates the canon was recognized very early and not invented by Constantine or the councils.",
      verse: "2 Peter 3:16 — 'As also in all his epistles, speaking in them of these things... they that are unlearned and unstable wrest, as they do also the other scriptures.'",
    },
    {
      title: "Athanasius's Easter Letter",
      year: "367 AD",
      location: "Alexandria, Egypt",
      tag: "Historical Record",
      summary: "Bishop Athanasius's 39th Easter letter is the first document listing exactly the 27 books of the New Testament we use today.",
      detail: "Athanasius wrote annual Easter letters to churches in his region. His 39th Festal Letter (367 AD) lists the same 27 books that comprise our New Testament — no more, no less. He wasn't inventing the canon but recognizing what the church had already received. The Council of Carthage (397 AD) ratified the same list. The canon was recognized through use over centuries, not imposed by emperors.",
      verse: "2 Timothy 3:16 — 'All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.'",
    },
    {
      title: "Justin Martyr's Apology",
      year: "c. 155 AD",
      location: "Rome",
      tag: "Historical Record",
      summary: "An open letter to Emperor Antoninus Pius defending Christianity — explicitly mentioning the 'memoirs of the apostles' (the Gospels) read in church on Sundays.",
      detail: "Justin Martyr's First Apology (c. 155 AD) describes a typical Sunday Christian gathering: 'On the day called Sunday, all who live in cities or in the country gather together... and the memoirs of the apostles or the writings of the prophets are read.' This proves the Gospels were already accepted as Scripture and read alongside the Old Testament during weekly worship — within 100 years of Jesus.",
      verse: "Luke 1:1-2 — 'Many have taken in hand to set forth in order a declaration of those things... even as they delivered them unto us, which from the beginning were eyewitnesses.'",
    },
    {
      title: "Pliny on Early Christian Worship",
      year: "c. 112 AD",
      location: "Bithynia (modern Turkey)",
      tag: "Historical Record",
      summary: "Roman governor Pliny describes Christians refusing to deny Christ even under torture — proving early believers held convictions strong enough to die for.",
      detail: "Beyond confirming Christian worship of Christ as God, Pliny's Letter 10.96 describes interrogations of Christians who 'refuse to invoke the gods, to offer sacrifice with wine and incense to your image, and to curse Christ.' He notes: 'Whatever the nature of their creed, stubbornness and inflexible obstinacy surely deserve to be punished.' Pliny's frustration over Christian willingness to die rather than recant testifies to the depth of their conviction.",
      verse: "Revelation 12:11 — 'They overcame him by the blood of the Lamb, and by the word of their testimony; and they loved not their lives unto the death.'",
    },
  ],

  "Fulfilled Prophecies": [
    {
      title: "Daniel's Prophecy of Four Empires",
      year: "Prophecy ~600 BC",
      location: "Babylon",
      tag: "Prophecy",
      summary: "Daniel 2 and 7 predicted four successive world empires — Babylon, Medo-Persia, Greece, and Rome — exactly the sequence that unfolded over the next 700 years.",
      detail: "Daniel interprets Nebuchadnezzar's dream of a statue (Daniel 2) and his own visions of beasts (Daniel 7) as predicting four kingdoms. History delivered: Babylon (605–539 BC), Medo-Persia (539–331 BC), Greece under Alexander (331–168 BC), and Rome (from 168 BC). Daniel even predicted Greece would split into four after Alexander's death (Daniel 8:8) — fulfilled exactly when Alexander's empire fragmented among his four generals: Cassander, Lysimachus, Seleucus, and Ptolemy.",
      verse: "Daniel 2:44 — 'In the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed.'",
    },
    {
      title: "Daniel's 70 Weeks Prophecy",
      year: "Prophecy ~538 BC",
      location: "Babylon",
      tag: "Prophecy",
      summary: "Daniel 9:24-27 predicted the Messiah would 'be cut off' exactly 483 years after the decree to rebuild Jerusalem — fulfilled in Jesus's crucifixion.",
      detail: "Daniel's '70 weeks' prophecy uses 'weeks of years.' From Artaxerxes' decree to rebuild Jerusalem (445 BC, Nehemiah 2:1-8) to the Messiah is 'seven weeks plus sixty-two weeks' = 69 weeks of years = 483 prophetic years (of 360 days). Calculated forward, this points to ~30 AD — the time of Jesus's ministry and crucifixion. Sir Robert Anderson's classic calculation in 'The Coming Prince' (1894) demonstrated this with stunning precision.",
      verse: "Daniel 9:26 — 'After threescore and two weeks shall Messiah be cut off, but not for himself.'",
    },
    {
      title: "Cyrus Named Before Birth",
      year: "Prophecy ~700 BC / Fulfilled 539 BC",
      location: "Israel/Babylon",
      tag: "Prophecy",
      summary: "Isaiah named King Cyrus of Persia as the one who would liberate the Jewish exiles — 150 years before Cyrus was born.",
      detail: "Isaiah 44:28 says: 'That saith of Cyrus, He is my shepherd, and shall perform all my pleasure: even saying to Jerusalem, Thou shalt be built; and to the temple, Thy foundation shall be laid.' Isaiah 45:1 calls Cyrus God's 'anointed.' Isaiah wrote ~700 BC. Cyrus the Great was born ~600 BC. He conquered Babylon in 539 BC and immediately decreed (Ezra 1:1-4) that the Jewish exiles could return and rebuild the Temple — naming the Lord by name in his decree.",
      verse: "Isaiah 45:1 — 'Thus saith the Lord to his anointed, to Cyrus, whose right hand I have holden.'",
    },
    {
      title: "The Fall of Nineveh",
      year: "Prophecy ~650 BC / Fulfilled 612 BC",
      location: "Nineveh (modern Iraq)",
      tag: "Prophecy",
      summary: "Nahum predicted Nineveh would be 'utterly cut off' and become 'empty, void, and waste' — the great Assyrian capital was destroyed and forgotten for 2,500 years.",
      detail: "Nahum's prophecy ~650 BC was scoffed at: Nineveh was the world's largest city, capital of the Assyrian Empire. Yet Nahum 1:8 predicted 'with an overrunning flood he will make an utter end of the place thereof.' In 612 BC, the Babylonians and Medes besieged Nineveh; the Tigris River flooded, destroying part of the wall. The city fell, was utterly destroyed, and disappeared from history so completely that for 2,500 years its location was unknown — until Layard's 1840s excavations.",
      verse: "Nahum 3:7 — 'Nineveh is laid waste: who will bemoan her?'",
    },
    {
      title: "The Fall and Restoration of Egypt",
      year: "Prophecy ~590 BC",
      location: "Egypt",
      tag: "Prophecy",
      summary: "Ezekiel predicted Egypt would become 'the basest of kingdoms' — never again ruling over the nations as in its glory days.",
      detail: "Ezekiel 29:14-15 wrote that Egypt would be restored as a 'base kingdom' but 'shall be the basest of the kingdoms; neither shall it exalt itself any more above the nations.' Egypt has never regained the imperial dominance it had under the Pharaohs. From Ezekiel's day to today (2,600+ years), Egypt has been ruled by Persians, Greeks, Romans, Arabs, Mamluks, Turks, French, British — always under foreign domination or in a diminished state. The pattern holds with unprecedented historical precision.",
      verse: "Ezekiel 29:15 — 'It shall be the basest of the kingdoms; neither shall it exalt itself any more above the nations.'",
    },
    {
      title: "The Scattering of Israel",
      year: "Prophecy ~1400 BC / Fulfilled 70–135 AD",
      location: "Israel/Worldwide",
      tag: "Prophecy",
      summary: "Moses predicted in detail that Israel would be scattered 'among all peoples, from the one end of the earth even unto the other' — fulfilled after the Roman destruction of Jerusalem.",
      detail: "Deuteronomy 28:64 (written ~1400 BC) predicted: 'The Lord shall scatter thee among all people, from the one end of the earth even unto the other.' After Rome destroyed Jerusalem in 70 AD and crushed the Bar Kokhba revolt in 135 AD, Jews were dispersed across the entire Roman Empire, eventually reaching every continent. The Jewish Diaspora has lasted nearly 1,900 years — exactly as predicted 3,400 years earlier.",
      verse: "Deuteronomy 28:64 — 'The Lord shall scatter thee among all people, from the one end of the earth even unto the other.'",
    },
    {
      title: "The Regathering of Israel",
      year: "Prophecy throughout OT / Fulfilled 1948",
      location: "Israel",
      tag: "Prophecy",
      summary: "Multiple prophets predicted Israel would be regathered to its land 'a second time' — fulfilled when the modern state of Israel was reborn in 1948.",
      detail: "Isaiah 11:11-12, Ezekiel 36-37, and many other passages predicted a second regathering of Israel from the four corners of the earth. After 1,878 years of exile, the United Nations voted in 1947 to re-establish a Jewish state, and Israel declared independence on May 14, 1948. No other ancient people group has ever been scattered, lost their language for centuries, and then returned to their homeland and revived their dead language (Hebrew). Mark Twain in 1867 visited Palestine and described it as 'a desolate country... a silent mournful expanse... we never saw a human being.' Today the same land flowers.",
      verse: "Ezekiel 37:21 — 'I will take the children of Israel from among the heathen... and bring them into their own land.'",
    },
    {
      title: "The Hebrew Language Revival",
      year: "Prophecy ~600 BC / Fulfilled 1880s–1948",
      location: "Israel",
      tag: "Prophecy",
      summary: "Zephaniah 3:9 predicted God would 'turn to the people a pure language' — Hebrew, dead as a spoken language for ~1,800 years, was revived as Israel's living national tongue.",
      detail: "Hebrew ceased to be a daily spoken language around 200 AD, surviving only in religious study. No other dead language has ever been revived as the everyday speech of a nation. Yet through the work of Eliezer Ben-Yehuda (starting 1881) and the Zionist movement, Hebrew became the official spoken language of Israel by 1948. Linguists call this unprecedented in human history. Zephaniah's 'pure language' prophecy remains one of the most concrete fulfillments of biblical text.",
      verse: "Zephaniah 3:9 — 'Then will I turn to the people a pure language.'",
    },
    {
      title: "Israel Blooming in the Desert",
      year: "Prophecy ~700 BC / Fulfilled 1948–present",
      location: "Israel",
      tag: "Prophecy",
      summary: "Isaiah 35:1 predicted 'the desert shall rejoice, and blossom as the rose' — modern Israel has transformed swamps and deserts into agricultural exporters.",
      detail: "When Mark Twain visited the Holy Land in 1867, he described it as 'desolate and unlovely... blistering, naked, treeless mountains.' Beginning in the late 1800s, Jewish immigrants drained malarial swamps, planted forests, and developed drip irrigation. Today Israel is a global agricultural and high-tech leader, exporting flowers, fruits, and water purification technology. The Negev Desert produces 40% of Israel's vegetables. The transformation is unprecedented and matches Isaiah's prophecy of desert renewal.",
      verse: "Isaiah 35:1 — 'The wilderness and the solitary place shall be glad for them; and the desert shall rejoice, and blossom as the rose.'",
    },
    {
      title: "The Virgin Birth Prophecy",
      year: "Prophecy ~700 BC / Fulfilled c. 5 BC",
      location: "Bethlehem",
      tag: "Prophecy",
      summary: "Isaiah 7:14 predicted the Messiah would be born of a virgin — a sign so unprecedented it required divine intervention to fulfill.",
      detail: "Isaiah 7:14 (c. 700 BC): 'Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel.' Some critics translate the Hebrew 'almah' as 'young woman' rather than 'virgin' — but the Septuagint translators (250 BC), 250 years before Christ, translated it 'parthenos' (virgin). Matthew 1:23 cites this prophecy as fulfilled in Mary. The Septuagint translation predates any possible Christian motivation, settling the meaning of the original prophecy.",
      verse: "Matthew 1:23 — 'Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel.'",
    },
    {
      title: "The Triumphal Entry on a Donkey",
      year: "Prophecy ~520 BC / Fulfilled 33 AD",
      location: "Jerusalem",
      tag: "Prophecy",
      summary: "Zechariah 9:9 predicted the Messiah would enter Jerusalem riding 'upon an ass, and upon a colt the foal of an ass' — fulfilled exactly on Palm Sunday.",
      detail: "Zechariah's prophecy specifies a king coming 'just, and having salvation; lowly, and riding upon an ass.' Jesus deliberately and publicly enacted this prophecy on Palm Sunday (Matthew 21:1-11), telling his disciples to fetch a donkey and her colt. Crowds laid palm branches and shouted 'Hosanna to the son of David!' The action was a deliberate Messianic claim, recognized as such by the religious leaders who immediately moved to arrest him.",
      verse: "Zechariah 9:9 — 'Rejoice greatly, O daughter of Zion... thy King cometh unto thee... lowly, and riding upon an ass.'",
    },
    {
      title: "Betrayal for 30 Pieces of Silver",
      year: "Prophecy ~520 BC / Fulfilled 33 AD",
      location: "Jerusalem",
      tag: "Prophecy",
      summary: "Zechariah 11:12-13 predicted the Messiah would be betrayed for exactly 30 pieces of silver, which would be cast into the temple and used to buy a potter's field.",
      detail: "Zechariah's prophecy is astonishingly specific: 'And they weighed for my price thirty pieces of silver. And the Lord said unto me, Cast it unto the potter: a goodly price that I was prised at of them.' Matthew 27:3-10 records Judas being paid exactly 30 pieces of silver to betray Jesus, then casting the coins down in the Temple. The chief priests, considering it blood money, used it to buy 'the potter's field' to bury strangers in. Three independently-fulfilled details from one prophecy.",
      verse: "Matthew 27:9-10 — 'They took the thirty pieces of silver... and gave them for the potter's field.'",
    },
    {
      title: "The Casting of Lots for Christ's Garments",
      year: "Prophecy ~1000 BC / Fulfilled 33 AD",
      location: "Jerusalem",
      tag: "Prophecy",
      summary: "Psalm 22 predicted soldiers would 'part my garments among them, and cast lots upon my vesture' — exactly what Roman soldiers did at the cross.",
      detail: "Psalm 22 (~1000 BC) describes details of crucifixion centuries before crucifixion was even invented as a method of execution: 'They pierced my hands and my feet... they part my garments among them, and cast lots upon my vesture.' John 19:23-24 records that Roman soldiers divided Jesus's clothing into four parts but cast lots for his seamless tunic, explicitly noting this fulfilled Psalm 22. Crucifixion was developed by the Persians around 600 BC and adopted by the Romans — yet David described it 1,000 years earlier.",
      verse: "Psalm 22:18 — 'They part my garments among them, and cast lots upon my vesture.'",
    },
    {
      title: "Christ's Bones Not Broken",
      year: "Prophecy throughout OT / Fulfilled 33 AD",
      location: "Jerusalem",
      tag: "Prophecy",
      summary: "Psalm 34:20 and Exodus 12:46 (Passover lamb law) predicted no bone of Messiah would be broken — fulfilled when Roman soldiers chose not to break Jesus's legs.",
      detail: "Roman crucifixion typically ended with 'crurifragium' — breaking the victim's legs to hasten death. John 19:31-36 records that soldiers did this to the two thieves crucified with Jesus, but found Jesus already dead. To confirm death, a soldier pierced his side instead. John explicitly notes this fulfilled Scripture: 'A bone of him shall not be broken' (Exodus 12:46, referring to the Passover lamb that pictured Christ).",
      verse: "John 19:36 — 'These things were done, that the scripture should be fulfilled, A bone of him shall not be broken.'",
    },
    {
      title: "Christ Sold by a Friend",
      year: "Prophecy ~1000 BC",
      location: "Jerusalem",
      tag: "Prophecy",
      summary: "Psalm 41:9 predicted the Messiah would be betrayed by 'mine own familiar friend, in whom I trusted, which did eat of my bread.'",
      detail: "Psalm 41:9 — written by David around 1000 BC — described betrayal by an intimate companion who shared meals with the Messiah. Jesus directly applied this prophecy to Judas Iscariot (John 13:18) at the Last Supper: 'I speak not of you all... but that the scripture may be fulfilled, He that eateth bread with me hath lifted up his heel against me.' Judas had been Jesus's chosen disciple for over three years.",
      verse: "Psalm 41:9 — 'Yea, mine own familiar friend, in whom I trusted, which did eat of my bread, hath lifted up his heel against me.'",
    },
  ],

  "Science Affirms Scripture": [
    {
      title: "The Bible Described Stars Beyond Counting",
      year: "Written ~1900 BC and ~600 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "God told Abraham (and later Jeremiah) the stars cannot be numbered — at a time when the naked eye could see only ~3,000 stars.",
      detail: "Genesis 22:17 (~1900 BC) and Jeremiah 33:22 (~600 BC) both compare descendants to 'the stars of the heaven' as innumerable. With the naked eye, only about 3,000 stars are visible. Greek astronomers like Ptolemy (~150 AD) catalogued just 1,022 stars. Yet the Bible insisted they could not be counted. Modern astronomy estimates 100 billion stars per galaxy and 100 billion galaxies — quite literally innumerable. The Bible's claim was scientifically premature but stunningly correct.",
      verse: "Jeremiah 33:22 — 'As the host of heaven cannot be numbered, neither the sand of the sea measured.'",
    },
    {
      title: "The Bible Described an Expanding Universe",
      year: "Written ~700 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Isaiah and other prophets describe God 'stretching out' the heavens — language matching the modern discovery that the universe is expanding.",
      detail: "Isaiah 40:22, 42:5, 44:24, 45:12, 51:13, Jeremiah 10:12, Zechariah 12:1, Job 9:8, Psalm 104:2 — at least 17 verses describe God 'stretching out' (Hebrew 'natah') the heavens. The Hebrew verb implies an ongoing process. Until the 1920s, astronomy assumed a static universe. Then Edwin Hubble proved galaxies are receding — the universe is literally expanding. The biblical 'stretching out' language predates this discovery by over 2,500 years.",
      verse: "Isaiah 40:22 — 'It is he that... stretcheth out the heavens as a curtain, and spreadeth them out as a tent to dwell in.'",
    },
    {
      title: "The Earth Hangs on Nothing",
      year: "Written ~2000 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Job 26:7 says God 'hangeth the earth upon nothing' — a remarkable astronomical insight at a time when most cultures believed the earth rested on giants, turtles, or pillars.",
      detail: "Ancient cosmologies almost universally placed the earth on something tangible: Atlas in Greek myth, four giant elephants on a turtle in Hindu myth, pillars in Mesopotamian myth. Yet Job — possibly the oldest book of the Bible — declares: 'He stretcheth out the north over the empty place, and hangeth the earth upon nothing.' The Hebrew word for 'nothing' is 'beli-mah' — literally 'not anything.' This matches modern astronomy's understanding that Earth orbits in space without physical support.",
      verse: "Job 26:7 — 'He stretcheth out the north over the empty place, and hangeth the earth upon nothing.'",
    },
    {
      title: "Light's Path and Darkness's Place",
      year: "Written ~2000 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Job 38:19 distinguishes between the 'way' of light and the 'place' of darkness — language matching modern physics: light has motion, darkness is the absence of motion.",
      detail: "Job 38:19 records God asking: 'Where is the way where light dwelleth? and as for darkness, where is the place thereof?' Modern physics shows that light has speed and direction (a 'way'), while darkness is simply the absence of light photons (a 'place,' i.e., a region). Ancient cultures often considered light and darkness equivalent opposing substances. Job's distinction matches what we now know.",
      verse: "Job 38:19 — 'Where is the way where light dwelleth? and as for darkness, where is the place thereof?'",
    },
    {
      title: "Springs of the Sea",
      year: "Written ~2000 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Job 38:16 mentions 'the springs of the sea' — a reality only confirmed in 1977 with the discovery of deep-ocean hydrothermal vents.",
      detail: "Job 38:16 records God asking: 'Hast thou entered into the springs of the sea? or hast thou walked in the search of the depth?' For most of human history, no one knew there were freshwater springs and hydrothermal vents on the ocean floor. In 1977, the deep submersible Alvin discovered hydrothermal vents on the ocean floor near the Galapagos Rift, supporting entire ecosystems. Job described this 4,000 years earlier.",
      verse: "Job 38:16 — 'Hast thou entered into the springs of the sea? or hast thou walked in the search of the depth?'",
    },
    {
      title: "Ocean Currents",
      year: "Written ~1000 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Psalm 8:8 references 'paths of the seas' — confirmed by oceanographer Matthew Maury in the 1850s, who founded modern oceanography after reading this verse.",
      detail: "Matthew Fontaine Maury, a US Navy commander known as 'the Pathfinder of the Seas,' read Psalm 8:8: 'The fowl of the air, and the fish of the sea, and whatsoever passeth through the paths of the seas.' Believing the Bible's reference to 'paths of the seas' implied ocean currents, he systematically charted them, founding modern oceanography. His charts dramatically reduced sailing times and saved countless lives. A statue of Maury holding a Bible stands in Richmond, Virginia.",
      verse: "Psalm 8:8 — 'The fowl of the air, and the fish of the sea, and whatsoever passeth through the paths of the seas.'",
    },
    {
      title: "Atomic-Level Composition",
      year: "Written ~60 AD",
      location: "Biblical Text",
      tag: "Science",
      summary: "Hebrews 11:3 says 'things which are seen were not made of things which do appear' — anticipating the discovery that visible matter is composed of invisible atoms and subatomic particles.",
      detail: "Hebrews 11:3 reads: 'Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.' Until the 19th–20th centuries, most thinkers assumed matter was made of smaller pieces of the same visible matter. Atomic theory and quantum physics revealed that matter is composed of atoms (mostly empty space) made of invisible subatomic particles, ultimately of energy fields. The biblical statement was a leap millennia ahead of human understanding.",
      verse: "Hebrews 11:3 — 'The worlds were framed by the word of God, so that things which are seen were not made of things which do appear.'",
    },
    {
      title: "The Origin of Universe from Nothing",
      year: "Written ~1400 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Genesis 1:1 — 'In the beginning God created the heaven and the earth' — exactly matches the modern Big Bang model: the universe had a definite beginning.",
      detail: "Until the 20th century, most scientists believed in an eternal, unchanging universe. Einstein's general relativity (1915), Hubble's expanding universe (1929), the cosmic microwave background (1964), and the inflation theory (1980s) all converged on a single model: the universe began at a finite point in the past from a singularity. Astrophysicist Robert Jastrow concluded: 'For the scientist who has lived by his faith in the power of reason, the story ends like a bad dream. He has scaled the mountains of ignorance... as he pulls himself over the final rock, he is greeted by a band of theologians who have been sitting there for centuries.'",
      verse: "Genesis 1:1 — 'In the beginning God created the heaven and the earth.'",
    },
    {
      title: "Life is in the Blood",
      year: "Written ~1400 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Leviticus 17:11 declares 'the life of the flesh is in the blood' — confirmed by modern medicine recognizing blood as the literal carrier of oxygen, nutrients, and immunity.",
      detail: "For most of history, blood was considered less important than other bodily fluids. Bloodletting was a common medical 'treatment' that killed many patients (including possibly George Washington). It wasn't until William Harvey's work in the 1620s that the circulation of blood was understood, and full appreciation of blood's life-giving role came in the 19th–20th centuries. Yet Leviticus declared 3,400 years earlier: 'The life of the flesh is in the blood.'",
      verse: "Leviticus 17:11 — 'For the life of the flesh is in the blood.'",
    },
    {
      title: "Circumcision on the Eighth Day",
      year: "Written ~2000 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "God commanded that male infants be circumcised on the 8th day after birth — exactly when vitamin K and prothrombin levels peak, allowing optimal blood clotting.",
      detail: "Genesis 17:12 (~2000 BC) commands circumcision on the 8th day. Modern hematology has revealed: at birth, vitamin K (essential for blood clotting) is low. Newborns have only ~30% of normal vitamin K. By day 8, vitamin K is at 110% of normal — the safest day for surgery in a baby's first weeks. Prothrombin (clotting factor II) follows the same curve, peaking around days 5–7 then settling at day 8. Dr. S.I. McMillen called this 'the safest day in a baby's first month.' The biblical command predates this knowledge by 3,800 years.",
      verse: "Genesis 17:12 — 'And he that is eight days old shall be circumcised among you, every man child in your generations.'",
    },
    {
      title: "Quarantine Saved Europe",
      year: "Mosaic law applied during the Black Death",
      location: "Europe (Middle Ages)",
      tag: "Science",
      summary: "When the Black Death killed 25 million Europeans, observant Jewish communities had dramatically lower death rates because they followed Mosaic Law's quarantine and hygiene rules.",
      detail: "Leviticus 13–15 mandates quarantining infected persons, washing after contact with the dead, washing clothing and bathing afterward, isolating bodily emissions, and burying waste. During the Black Death (1347–1351), Jewish communities in Europe — observing these laws — had significantly lower mortality. Tragically, this led to false accusations that Jews caused the plague by 'poisoning wells.' The germ theory of disease wouldn't be established until Pasteur (1860s), yet Mosaic Law had been protecting health for 3,000 years.",
      verse: "Leviticus 15:13 — 'He shall wash his clothes, and bathe his flesh in running water, and shall be clean.'",
    },
    {
      title: "Sanitation Outside the Camp",
      year: "Written ~1400 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Deuteronomy 23:12-13 commanded the Israelites to bury their waste outside the camp — a sanitation principle Western armies didn't adopt until the 19th century.",
      detail: "During the American Civil War (1861–1865) more soldiers died of typhoid, dysentery, and cholera than died in combat — because Union and Confederate camps lacked basic sanitation. Yet Deuteronomy 23 commanded Israelites 3,300 years earlier to designate a place outside camp and to dig a hole, deposit waste, and cover it. Florence Nightingale's reforms during the Crimean War (1850s) were essentially rediscovering Mosaic sanitation principles. The Bible's instructions saved lives invisible to ancient peoples.",
      verse: "Deuteronomy 23:13 — 'Thou shalt have a paddle... and shalt dig therewith, and shalt turn back and cover that which cometh from thee.'",
    },
    {
      title: "Animals That Chew the Cud and Have Cloven Hooves",
      year: "Written ~1400 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Leviticus 11 prohibits eating animals that don't both chew the cud AND have split hooves — a remarkably precise zoological classification that modern science vindicates.",
      detail: "Leviticus 11:3-7 lists clean and unclean animals with surgical precision. Specifically prohibited: the camel (chews cud but no split hooves), hare (chews cud but no split hooves), and pig (split hooves but doesn't chew cud). Modern parasitology has shown all three carry parasites and diseases dangerous to humans (camel: brucellosis; hare: tularemia; pig: trichinosis, tapeworms). The categorization shows knowledge of animal physiology and disease vectors millennia ahead of its time.",
      verse: "Leviticus 11:3 — 'Whatsoever parteth the hoof, and is clovenfooted, and cheweth the cud, among the beasts, that shall ye eat.'",
    },
    {
      title: "Forbidden Fats and Heart Disease",
      year: "Written ~1400 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Leviticus 7:23 forbids eating animal fat — a dietary restriction modern medicine echoes as protection against cardiovascular disease.",
      detail: "Leviticus 7:23-25 explicitly prohibits eating the fat of cattle, sheep, or goats: 'Ye shall eat no manner of fat, of ox, or of sheep, or of goat.' Modern cardiology has confirmed that high consumption of saturated animal fats is a major contributor to atherosclerosis, heart disease, and stroke. The American Heart Association recommends limiting saturated fat — essentially echoing Mosaic dietary principles given 3,400 years ago.",
      verse: "Leviticus 7:23 — 'Ye shall eat no manner of fat, of ox, or of sheep, or of goat.'",
    },
    {
      title: "Joy and Laughter as Medicine",
      year: "Written ~950 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Proverbs 17:22 says 'a merry heart doeth good like a medicine' — research now confirms positive emotion measurably boosts immunity and recovery.",
      detail: "Proverbs 17:22 (~950 BC): 'A merry heart doeth good like a medicine: but a broken spirit drieth the bones.' Modern psychoneuroimmunology has confirmed: laughter reduces stress hormones (cortisol, epinephrine), increases T-cell production, releases endorphins, and improves cardiovascular health. Long-term depression and chronic stress measurably weaken bone density and immune function. Norman Cousins's classic book 'Anatomy of an Illness' (1979) documented his recovery from disease using laughter therapy — vindicating Solomon's ancient observation.",
      verse: "Proverbs 17:22 — 'A merry heart doeth good like a medicine: but a broken spirit drieth the bones.'",
    },
    {
      title: "Wind Currents and the Hydrological Cycle",
      year: "Written ~950 BC",
      location: "Biblical Text",
      tag: "Science",
      summary: "Ecclesiastes 1:6 describes the wind's circular pattern — atmospheric scientists confirm the global circulation of air follows the patterns Solomon described.",
      detail: "Ecclesiastes 1:6 (~950 BC): 'The wind goeth toward the south, and turneth about unto the north; it whirleth about continually, and the wind returneth again according to his circuits.' Modern atmospheric science describes the Hadley cells, polar cells, and trade winds that circulate air around the globe in patterns matching Solomon's description. The 'circuits' (round paths) of wind weren't formally mapped until the 17th–18th centuries.",
      verse: "Ecclesiastes 1:6 — 'The wind whirleth about continually, and the wind returneth again according to his circuits.'",
    },
  ],
};
